# Generated by Django 5.1.1 on 2026-03-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('proteina', models.FloatField()),
                ('carboidrato', models.FloatField()),
                ('gordura', models.FloatField()),
                ('calorias', models.FloatField()),
                ('custo', models.FloatField()),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
    ]
