# Generated by Django 5.1.1 on 2026-03-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aliemnto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('calorias_100g', models.FloatField()),
                ('proteina_100g', models.FloatField()),
                ('gordura_100g', models.FloatField()),
                ('preçp_kg', models.FloatField()),
            ],
        ),
    ]
