# Generated by Django 5.1.1 on 2026-03-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('objetivo', models.CharField(choices=[('emagrecer', 'Emagrecer'), ('manter', 'Manter peso'), ('massa', 'Ganhar massa')], max_length=20)),
                ('tipo_deficit', models.CharField(choices=[('manutencao', 'Manutenção'), ('leve', 'Déficit leve'), ('moderado', 'Déficit Moderado'), ('agressivo', 'Déficit agressivo')], max_length=20)),
                ('atividade', models.CharField(choices=[('sedentario', 'Sedentário'), ('leve', 'Leve'), ('moderado', 'Moderado'), ('intenso', 'Intenso')], max_length=20)),
            ],
        ),
    ]
