# Generated by Django 5.1.1 on 2026-03-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_deficit',
            field=models.CharField(choices=[('manutencao', 'Manutenção'), ('leve', 'Déficit leve'), ('moderado', 'Déficit Moderado'), ('agressivo', 'Déficit agressivo')], default='moderado', max_length=20),
            preserve_default=False,
        ),
    ]
