# Generated by Django 5.1.1 on 2026-03-17 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_tipo_deficit'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ativiade',
            field=models.CharField(choices=[('sedentario', 'Sedentário'), ('leve', 'Leve'), ('moderado', 'Moderado'), ('intenso', 'Intenso')], default='moderado', max_length=20),
            preserve_default=False,
        ),
    ]
